[package]
name = "huaji-lang"
version = "0.1.0"
authors = ["luojia65 <me@luojia.cc>"]
edition = "2018"
build = "build.rs"

[dependencies]
cranelift = "*"

[build-dependencies]
peg = { version = "*" }
